/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POS;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import POS.Variables;

/**
 *
 * @author jennifer
 */


public class POS_System extends javax.swing.JFrame {

    // database EmployeeDataBase
    // ID: owner
    // PW: password
    

    /**
     * Creates new form POS_System
     */
    public POS_System() {
        initComponents();
        Door.setEnabled(false);
        Kitchen.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pane_Tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Table5 = new javax.swing.JButton();
        Table2 = new javax.swing.JButton();
        Table4 = new javax.swing.JButton();
        Table3 = new javax.swing.JButton();
        Door = new javax.swing.JButton();
        Kitchen = new javax.swing.JButton();
        Table7 = new javax.swing.JButton();
        Table1 = new javax.swing.JButton();
        Table8 = new javax.swing.JButton();
        Table6 = new javax.swing.JButton();
        Table10 = new javax.swing.JButton();
        Table9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        TakeOut1 = new javax.swing.JButton();
        TakeOut5 = new javax.swing.JButton();
        TakeOut9 = new javax.swing.JButton();
        TakeOut2 = new javax.swing.JButton();
        TakeOut3 = new javax.swing.JButton();
        TakeOut4 = new javax.swing.JButton();
        TakeOut6 = new javax.swing.JButton();
        TakeOut10 = new javax.swing.JButton();
        TakeOut7 = new javax.swing.JButton();
        TakeOut11 = new javax.swing.JButton();
        TakeOut8 = new javax.swing.JButton();
        TakeOut12 = new javax.swing.JButton();
        Panel_Right = new javax.swing.JPanel();
        Clock_In_Out = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Table5.setText("5");
        Table5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table5ActionPerformed(evt);
            }
        });

        Table2.setText("2");
        Table2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table2ActionPerformed(evt);
            }
        });

        Table4.setText("4");
        Table4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table4ActionPerformed(evt);
            }
        });

        Table3.setText("3");
        Table3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table3ActionPerformed(evt);
            }
        });

        Door.setBackground(new java.awt.Color(153, 153, 153));
        Door.setText("Door");
        Door.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoorActionPerformed(evt);
            }
        });

        Kitchen.setText("Kitchen");
        Kitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KitchenActionPerformed(evt);
            }
        });

        Table7.setText("7");
        Table7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table7ActionPerformed(evt);
            }
        });

        Table1.setText("1");
        Table1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table1ActionPerformed(evt);
            }
        });

        Table8.setText("8");
        Table8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table8ActionPerformed(evt);
            }
        });

        Table6.setText("6");
        Table6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table6ActionPerformed(evt);
            }
        });

        Table10.setText("10");
        Table10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table10ActionPerformed(evt);
            }
        });

        Table9.setText("9");
        Table9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Table4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Table3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Table2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Table1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Table5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Table6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Table7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Table8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Table10, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(Table9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kitchen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Door, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Door)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Table5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Table8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Table10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Table7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(Table3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Table9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Table6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Table1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kitchen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Pane_Tab.addTab("Tables", jPanel1);

        TakeOut1.setText("TakeOut #1");
        TakeOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut1ActionPerformed(evt);
            }
        });

        TakeOut5.setText("TakeOut #5");
        TakeOut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut5ActionPerformed(evt);
            }
        });

        TakeOut9.setText("TakeOut #9");
        TakeOut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut9ActionPerformed(evt);
            }
        });

        TakeOut2.setText("TakeOut #2");
        TakeOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut2ActionPerformed(evt);
            }
        });

        TakeOut3.setText("TakeOut #3");
        TakeOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut3ActionPerformed(evt);
            }
        });

        TakeOut4.setText("TakeOut #4");
        TakeOut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut4ActionPerformed(evt);
            }
        });

        TakeOut6.setText("TakeOut #6");
        TakeOut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut6ActionPerformed(evt);
            }
        });

        TakeOut10.setText("TakeOut #10");
        TakeOut10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut10ActionPerformed(evt);
            }
        });

        TakeOut7.setText("TakeOut #7");
        TakeOut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut7ActionPerformed(evt);
            }
        });

        TakeOut11.setText("TakeOut #11");
        TakeOut11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut11ActionPerformed(evt);
            }
        });

        TakeOut8.setText("TakeOut #8");
        TakeOut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut8ActionPerformed(evt);
            }
        });

        TakeOut12.setText("TakeOut #12");
        TakeOut12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOut12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TakeOut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TakeOut5, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TakeOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TakeOut6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TakeOut9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TakeOut10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TakeOut11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TakeOut12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TakeOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TakeOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TakeOut7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TakeOut8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TakeOut4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(TakeOut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TakeOut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TakeOut3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TakeOut5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TakeOut7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TakeOut8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TakeOut6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TakeOut11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(TakeOut9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TakeOut10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TakeOut12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Pane_Tab.addTab("Take-Out", jPanel3);

        Clock_In_Out.setText("Clock In/Out");
        Clock_In_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clock_In_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_RightLayout = new javax.swing.GroupLayout(Panel_Right);
        Panel_Right.setLayout(Panel_RightLayout);
        Panel_RightLayout.setHorizontalGroup(
            Panel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clock_In_Out)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_RightLayout.setVerticalGroup(
            Panel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Clock_In_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jMenu1.setText("JENN'S SYSTEM");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_Tab)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Panel_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoorActionPerformed
        // disabled
    }//GEN-LAST:event_DoorActionPerformed

    private void Table6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table6ActionPerformed
    Variables.tableNum = "6";
    Variables.takeOut = false;
    newOrder();
   
    }//GEN-LAST:event_Table6ActionPerformed

    private void Table1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table1ActionPerformed
    Variables.tableNum = "1";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table1ActionPerformed

    private void Table2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table2ActionPerformed
    Variables.tableNum = "2";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table2ActionPerformed

    private void Table3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table3ActionPerformed
    Variables.tableNum = "3";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table3ActionPerformed

    private void Table4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table4ActionPerformed
    Variables.tableNum = "4";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table4ActionPerformed

    private void Table5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table5ActionPerformed
    Variables.tableNum = "5";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table5ActionPerformed

    private void Table7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table7ActionPerformed
    Variables.tableNum = "7";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table7ActionPerformed

    private void Table8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table8ActionPerformed
    Variables.tableNum = "8";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table8ActionPerformed

    private void Table9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table9ActionPerformed
    Variables.tableNum = "9";
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table9ActionPerformed

    private void Table10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table10ActionPerformed
    Variables.takeOut = false;
    newOrder();
    }//GEN-LAST:event_Table10ActionPerformed

    private void KitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KitchenActionPerformed
        // disabled
    }//GEN-LAST:event_KitchenActionPerformed

    private void TakeOut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut5ActionPerformed
    Variables.tableNum = "TakeOut5";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut5ActionPerformed

    private void Clock_In_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clock_In_OutActionPerformed
        Clock_In_Out Window = new Clock_In_Out();
        Window.setVisible(true);
    }//GEN-LAST:event_Clock_In_OutActionPerformed

    private void TakeOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut1ActionPerformed
    Variables.tableNum = "TakeOut1";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut1ActionPerformed

    private void TakeOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut2ActionPerformed
    Variables.tableNum = "TakeOut2";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut2ActionPerformed

    private void TakeOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut3ActionPerformed
    Variables.tableNum = "TakeOut3";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut3ActionPerformed

    private void TakeOut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut4ActionPerformed
    Variables.tableNum = "TakeOut4";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut4ActionPerformed

    private void TakeOut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut6ActionPerformed
    Variables.tableNum = "TakeOut6";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut6ActionPerformed

    private void TakeOut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut7ActionPerformed
    Variables.tableNum = "TakeOut7";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut7ActionPerformed

    private void TakeOut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut8ActionPerformed
    Variables.tableNum = "TakeOut8";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut8ActionPerformed

    private void TakeOut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut9ActionPerformed
    Variables.tableNum = "TakeOut9";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut9ActionPerformed

    private void TakeOut10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut10ActionPerformed
    Variables.tableNum = "TakeOut10";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut10ActionPerformed

    private void TakeOut11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut11ActionPerformed
    Variables.tableNum = "TakeOut11";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut11ActionPerformed

    private void TakeOut12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOut12ActionPerformed
    Variables.tableNum = "TakeOut12";
    Variables.takeOut = true;
    Variables.server = "";
    Variables.guestNum = "";
    Order Window = new Order();
    Window.setVisible(true);
    }//GEN-LAST:event_TakeOut12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS_System().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clock_In_Out;
    private javax.swing.JButton Door;
    private javax.swing.JButton Kitchen;
    private javax.swing.JTabbedPane Pane_Tab;
    private javax.swing.JPanel Panel_Right;
    private javax.swing.JButton Table1;
    private javax.swing.JButton Table10;
    private javax.swing.JButton Table2;
    private javax.swing.JButton Table3;
    private javax.swing.JButton Table4;
    private javax.swing.JButton Table5;
    private javax.swing.JButton Table6;
    private javax.swing.JButton Table7;
    private javax.swing.JButton Table8;
    private javax.swing.JButton Table9;
    private javax.swing.JButton TakeOut1;
    private javax.swing.JButton TakeOut10;
    private javax.swing.JButton TakeOut11;
    private javax.swing.JButton TakeOut12;
    private javax.swing.JButton TakeOut2;
    private javax.swing.JButton TakeOut3;
    private javax.swing.JButton TakeOut4;
    private javax.swing.JButton TakeOut5;
    private javax.swing.JButton TakeOut6;
    private javax.swing.JButton TakeOut7;
    private javax.swing.JButton TakeOut8;
    private javax.swing.JButton TakeOut9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void newOrder() {
       Select_Table Window;
        try {
            Window = new Select_Table();
            Window.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(POS_System.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
